# Generated by Django 4.2.3 on 2023-07-22 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erapi', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
