# Generated by Django 4.1.3 on 2023-08-17 11:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erapi', '0005_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesposts',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
