# Generated by Django 4.1.3 on 2023-08-29 12:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erapi', '0006_alter_gamesposts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesposts',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
