# Generated by Django 4.1.3 on 2023-08-29 20:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erapi', '0008_alter_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='link',
        ),
        migrations.AddField(
            model_name='posts',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
